apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentiment-app-frontend-deployment
  labels:
    app: sentiment-app-frontend-dep
  namespace: sentiment-app-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sentiment-app-frontend
  template:
    metadata:
      labels:
        app: sentiment-app-frontend
    spec:
      containers:
        - name: sentiment-app-frontend
          image: normanboettcher/sentiment-app:frontend-3.0.1
          ports:
            - containerPort: 80
          env:
            - name: VITE_MODEL_API_URL
              value: "sentiment-app.predict.service"