#stage 1: build
FROM node:20.9.0-alpine AS builder

WORKDIR /app
RUN corepack enable
COPY package.json yarn.lock ./
RUN yarn set version 4.9.1
#install dependencies
RUN yarn install

#copy the rest of the project
COPY . .

FROM builder AS dev
CMD ["npm", "run", "dev"]
