# ---- Base image for build and test ----
FROM python:3.12-slim AS build

#set environment
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /apps

#install dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

COPY pip.conf /etc/

RUN pip install --upgrade pip setuptools pytest pytest-cov

COPY common-requirements.txt /apps
COPY sentiment-model/requirements.txt /apps/sentiment-model/
COPY rest-api/requirements.txt /apps/rest-api/
COPY wheels wheels/
#install required dependencies first
RUN pip install --no-index --find-links=./wheels -r common-requirements.txt \
                                        -r sentiment-model/requirements.txt \
                                        -r rest-api/requirements.txt

#copy rest of code
COPY sentiment-model sentiment-model/
COPY rest-api rest-api/

#build wheels
RUN pip wheel ./sentiment-model/ -w ./wheels
RUN pip wheel ./rest-api -w ./wheels

#install sentiment-model
RUN pip install ./wheels/sentiment_model-*.whl \
    && pip install ./wheels/sentiment_model_api*.whl

# ---- Runtime image ----
FROM python:3.12-slim AS runtime
WORKDIR /app
COPY --from=build /apps/wheels ./wheels
COPY ./common-requirements.txt .
COPY rest-api/requirements.txt .

RUN pip install --upgrade pip
RUN pip install --no-index --find-links=./wheels -r common-requirements.txt \
        -r requirements.txt \
        ./wheels/sentiment_model-*.whl \
        ./wheels/sentiment_model_api-*.whl

#clean up
RUN rm -rf ./wheels
#copy only runtime source files
COPY --from=build /apps/rest-api/src ./rest-api/src
#workdir with source files
WORKDIR /app/rest-api/src/model_api
#expose port
EXPOSE 5000

#ENTRYPOINT ["python", "main.py"]