version: '3.9'
services:
  predict.sentiment.com:
    build:
      context: frontend/
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    networks:
      - sentiment-net
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development

  sentiment.app.api:
    build:
      context: .
      dockerfile: rest-api/Dockerfile
    restart: unless-stopped
    networks:
      - sentiment-net
    ports:
      - "5000:5000"
    expose:
      - "5000"
    #environment:
      #ALLOWED_ORIGINS: http://localhost:3000
networks:
  sentiment-net:
    driver: bridge

