[tool.tox]
envlist = ["sentiment_model-test",
    "sentiment_model-lint",
    "sentiment_model-format",
    "sentiment_api-test",
    "sentiment_api-lint",
    "sentiment_api-format"
]

[tool.tox.env.sentiment_model-test]
description = "Run tests of senitment-model project"
allowlist_externals = ["sh"]
commands = [
    ["sh", "-c", "cd sentiment-model && pytest --cov=sentiment_model --cov-report=term-missing tests/"],
]
deps = [
    "./sentiment-model",
    "pytest",
    "pytest-cov",
    "-rsentiment-model/requirements.txt",
    "-rcommon-requirements.txt"
]

[tool.tox.env.sentiment_model-lint]
description = "Run linter for sentiment-model project"
allowlist_externals = ["sh"]
deps = ["flake8"]
commands = [
    ["sh", "-c", "cd sentiment-model && flake8 src/"]
]

[tool.tox.env.sentiment_model-format]
description = "Run format for sentirment-model project"
allowlist_externals = ["sh"]
deps = ["black"]
commands = [
    ["sh", "-c", "cd sentiment-model && black src/"],
]


[tool.tox.env.sentiment_api-test]
description = "Run tests of rest-api"
allowlist_externals = ["sh"]
commands = [
    ["sh", "-c", "cd rest-api && pytest --cov=model_api --cov-report=term-missing tests/"],
]
deps = [
    "./rest-api",
    "pytest",
    "pytest-cov",
    "-rrest-api/requirements.txt",
    "-e ./sentiment-model",
    "-rcommon-requirements.txt"
]

[tool.tox.env.sentiment_api-lint]
description = "Run linter for rest-api project"
allowlist_externals = ["sh"]
deps = ["flake8"]
commands = [
    ["sh", "-c", "cd rest-api && flake8 src/"]
]

[tool.tox.env.sentiment_api-format]
description = "Run format for rest-api project"
allowlist_externals = ["sh"]
deps = ["black"]
commands = [
    ["sh", "-c", "cd rest-api && black src/"],
]


