apiVersion: v1
kind: Service
metadata:
  name: sentiment-frontend-service
  namespace: sentiment-app-dev
spec:
  type: NodePort
  selector:
    app: sentiment-app-frontend
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 3000
      nodePort: 31002
