apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prometheus-service-discovery
  namespace: sentiment-app-dev
rules:
  - apiGroups: [ "" ]
    resources:
      - services
      - endpoints
      - pods
    verbs:
      - get
      - list
      - watch
