apiVersion: v1
kind: Service
metadata:
  name: model-api-service
  namespace: sentiment-app-dev
  labels:
    app: model-api-service
spec:
  type: NodePort
  selector:
    app: model-api
  ports:
    - name: http
      protocol: TCP
      port: 8081
      targetPort: 5000
      nodePort: 31001